[tool.poetry]
name = "symmeplot"
version = "0.0.1"
description = "SymPy Mechanics Plotter"
authors = ["TJStienstra <timostienstra00@gmail.com>"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.9"
sympy = "^1.12"
numpy = "^1.26.0"
matplotlib = "^3.8.2"

[tool.poetry.group.lint.dependencies]
ruff = "^0.1.14"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.4"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-rtd-theme = "^2.0.0"
jupyter-sphinx = "^0.5.3"
autodocsumm = "^0.2.12"
ipykernel = "^6.29.0"

[project.urls]
"Homepage" = "https://github.com/TJStienstra/symmeplot"
"Bug Tracker" = "https://github.com/TJStienstra/symmeplot/issues"
"Documentation" = "https://tjstienstra.github.io/symmeplot/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py37"
select = ["A", "B", "C", "D", "E", "F", "I", "N", "Q", "W", "NPY", "RUF", "SIM", "TID",
          "T20", "UP"]
ignore = ["A003", "C901", "D100", "D105", "D107", "D203", "D213", "RUF200"]
show-source = true

[tool.ruff.per-file-ignores]
"docs/conf.py" = ["A001"]  # Ignore copyright shadowing
"*/__init__.py" = ["D104"]
"tests/*" = ["D", "N806", "S101"]
"src/symmeplot/plot_artists.py" = ["D102"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
