name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry==1.7.1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
