name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  #----------------------------------- code-quality -----------------------------------#

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: poetry install --with lint
      - name: Lint with ruff
        run: poetry run ruff .

  #-------------------------------------- tests ---------------------------------------#

  tests:
    needs: code-quality

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --with test
      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 python3-opengl
      - name: Run tests
        run: poetry run pytest

  #------------------------------------ docs-tests ------------------------------------#

  test_docs_job:
    needs: code-quality

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.7.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --with docs
      - name: make the sphinx docs
        run: |
          poetry run make -C docs clean
          poetry run make -C docs html
